### ISSUE TITLE
Publish to maven local problem

### ISSUE THREAD

**Issue by corlaez** [nazmulidris/color-console#2]
After running publish to local maven I have been unable to consume the library from local.
It keeps saying it is unable to find the library requested.
I did called mavenLocal()

**Comment by nazmulidris** [comment]
I moved the library to jitpack a while back and am no longer using GPR or maven (deprecated 2021-04-12) .
Here's more info on this:
1. https://developerlife.com/2021/02/06/publish-kotlin-library-as-gradle-dep/
2. https://github.com/nazmulidris/color-console#how-to-import-this-dependency-into-gradle-using-jitpack

**Comment by corlaez** [comment]
Right, Jitpack works fine, but I was wondering if you know how to make it work both in jitpack and make the publishToMavenLocal work as well.
